# Numpy Playlist
* https://www.youtube.com/watch?v=6puhu5ulFSE&list=PLmRclvVt5Dtlgy6PordwKtiUr7fwjuhfz&index=1

In [3]:
import numpy as np
a : list[int] = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [4]:
myArr = np.array(a)
myArr

array([1, 2, 3, 4])

In [5]:
user_input = int(input('Enter array size'))
data = []
for i in range(user_input):
    array_data = int(input(f'Enter {i+1} number'))
    data.append(array_data)
my_array = np.array(data)
my_array


array([3, 2, 3, 4])

# Two Diamensional Arrays

In [6]:
data = [[1,2,3], [4,5,6],[7,8,9]]
myArray = np.array(data)
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
myArray.ndim

2

In [8]:
myArray.shape

(3, 3)

In [10]:
# print 0
newArray = np.zeros(7)
newArray

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
newArray = np.zeros((2, 3))
newArray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# For Diagonals
newArray = np.eye(5)
newArray

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# make diagonals 1 and rest 0
newArray = np.eye(3,4)
newArray

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
# pulls diagonals
myArray = np.diag([2,3,4])
myArray

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [15]:
np.diag(myArray)

array([2, 3, 4])

In [16]:
# generate random numbers in a given range (start, end not included, values)
myArray = np.random.randint(2,89,5)
myArray

array([65, 85,  7, 61, 35])

In [17]:
# generate random numbers between 0 and 1
myArray = np.random.rand(4)
myArray

array([0.35919953, 0.91520916, 0.46890207, 0.2534493 ])

In [18]:
# generate values close to 1 and could be -ve
myArray = np.random.randn(4)
myArray

array([ 3.44951003,  0.38025873, -0.63757072, -0.22564972])

In [19]:
# array conversions (reshaping)
myArray = np.random.randint(2,77,12)
myArray

array([36, 65, 50, 15, 41, 49, 22, 60, 34, 31, 53, 12])

In [20]:
myArray.reshape(3,4)

array([[36, 65, 50, 15],
       [41, 49, 22, 60],
       [34, 31, 53, 12]])

In [21]:
myArray.reshape(12)
myArray

array([36, 65, 50, 15, 41, 49, 22, 60, 34, 31, 53, 12])

In [22]:
# auto-populate the -1 column
# must be stored in a new variable
dataArray = np.random.randint(2,77,12)
data = dataArray.reshape(4,-1)
data

array([[35, 12, 50],
       [29, 51, 41],
       [65, 68, 48],
       [ 3,  4, 26]])

In [85]:
# seed function maintains the values and not chang
np.random.seed(1)
dataArray = np.random.randint(2,77,12)
dataArray

array([39, 14, 74, 11,  7, 66, 18,  3, 73,  8, 27, 52])

In [25]:
# 2D array with user input. A bit tricky and needs practice
# https://www.youtube.com/watch?v=iFJHiZkLIi8&list=PLmRclvVt5Dtlgy6PordwKtiUr7fwjuhfz&index=10

In [26]:
# Slicing and Indexing of 2D arrays
data

array([[35, 12, 50],
       [29, 51, 41],
       [65, 68, 48],
       [ 3,  4, 26]])

In [27]:
data[2][1]

68

In [66]:
# Slicing Syntax => data[row_range, column_range]
data

array([[14, 12,  2],
       [62, 26, 59],
       [58,  3, 22],
       [49, 16, 40]])

In [28]:
data[1:3]

array([[29, 51, 41],
       [65, 68, 48]])

In [29]:
data[1:3,1:3]

array([[51, 41],
       [68, 48]])

In [30]:
newArray = np.random.randint(2,66,30)
newArray

array([22, 64, 39, 20, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [31]:
multiArray = newArray.reshape(6,-1)
multiArray

array([[22, 64, 39, 20, 22],
       [13, 62, 44, 30, 31],
       [16, 52,  6, 25, 25],
       [43, 51, 57, 32, 34],
       [24, 15, 43, 11,  9],
       [65, 63, 24, 59,  3]])

In [32]:
multiArray[3:6,2:5]

array([[57, 32, 34],
       [43, 11,  9],
       [24, 59,  3]])

In [33]:
# view vs copy
newArray

array([22, 64, 39, 20, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [39]:
myView = newArray[2:4]
myView

array([39, 20])

In [40]:
myView[:] = 0
myView

array([0, 0])

In [41]:
newArray

array([22, 64,  0,  0, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [45]:
myCopy = newArray[4:8].copy()
myCopy[:] = 5
myCopy


array([5, 5, 5, 5])

In [46]:
newArray

array([22, 64,  0,  0, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [51]:
# Conditional statements
data = np.arange(1, 16)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
data > 10


array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [56]:
data[data > 10]

array([11, 12, 13, 14, 15])

In [57]:
data[data % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [59]:
# we can also update
data[data > 10] = 0
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  0,  0,  0,  0])

In [60]:
data.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 0,  0,  0,  0,  0]])

# creating random matrix with numpy

In [63]:
# 1st Option
records = np.arange(21, 51)
records

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [64]:
records.reshape(6, 5)

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [81]:
# 2nd Option
from nptyping import NDArray, Shape, Int64
total : int = 40
s1 : NDArray[Shape[str(total)], Int64] = np.random.randint(10, 20, (total, 5))
s1

array([[19, 10, 11, 12, 14],
       [16, 10, 16, 10, 10],
       [12, 16, 14, 11, 15],
       [18, 12, 12, 16, 15],
       [11, 12, 17, 16, 17],
       [14, 15, 17, 12, 13],
       [17, 14, 11, 15, 18],
       [13, 11, 10, 18, 18],
       [14, 14, 12, 16, 18],
       [15, 17, 17, 19, 17],
       [18, 18, 19, 14, 19],
       [16, 12, 13, 14, 13],
       [15, 12, 16, 19, 16],
       [10, 14, 17, 13, 17],
       [16, 15, 10, 12, 19],
       [19, 13, 12, 15, 11],
       [17, 19, 18, 17, 13],
       [11, 17, 13, 17, 19],
       [13, 18, 17, 14, 19],
       [18, 19, 15, 16, 10],
       [13, 13, 15, 11, 18],
       [15, 12, 13, 13, 17],
       [16, 18, 17, 18, 12],
       [17, 17, 18, 17, 12],
       [13, 17, 10, 14, 10],
       [18, 19, 14, 12, 17],
       [18, 13, 14, 10, 17],
       [17, 19, 18, 17, 11],
       [14, 18, 13, 19, 14],
       [12, 19, 10, 11, 12],
       [18, 13, 16, 19, 17],
       [18, 16, 19, 19, 19],
       [18, 12, 11, 16, 14],
       [19, 13, 11, 13, 16],
       [15, 14

In [82]:
# convert to matrix with pandas
import pandas as pd
ss1 : pd.DataFrame = pd.DataFrame(s1, columns=['s1', 's2', 's3', 's4', 's5'])
ss1

s1  s2  s3  s4  s5
0   19  10  11  12  14
1   16  10  16  10  10
2   12  16  14  11  15
3   18  12  12  16  15
4   11  12  17  16  17
5   14  15  17  12  13
6   17  14  11  15  18
7   13  11  10  18  18
8   14  14  12  16  18
9   15  17  17  19  17
10  18  18  19  14  19
11  16  12  13  14  13
12  15  12  16  19  16
13  10  14  17  13  17
14  16  15  10  12  19
15  19  13  12  15  11
16  17  19  18  17  13
17  11  17  13  17  19
18  13  18  17  14  19
19  18  19  15  16  10
20  13  13  15  11  18
21  15  12  13  13  17
22  16  18  17  18  12
23  17  17  18  17  12
24  13  17  10  14  10
25  18  19  14  12  17
26  18  13  14  10  17
27  17  19  18  17  11
28  14  18  13  19  14
29  12  19  10  11  12
30  18  13  16  19  17
31  18  16  19  19  19
32  18  12  11  16  14
33  19  13  11  13  16
34  15  14  19  16  18
35  14  10  13  19  13
36  18  12  18  17  14
37  16  14  17  15  15
38  14  17  17  12  18
39  11  17  11  15  11

In [108]:
np.random.seed(1)
result = np.random.randint(3, 11, 10)

result.reshape(5, 2)

array([[ 8,  6],
       [ 7,  3],
       [10,  4],
       [ 6,  8],
       [10,  3]])

In [119]:
np.random.seed(122)
result = np.random.randint(1, 21, 9)
result = result.reshape(3, 3)
result

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [121]:
np.sum(result, axis=1)

array([40, 46, 30])

# Practice Questions

In [130]:
# 1.
import numpy as np
# 2 & 3.
data = np.arange(2, 13)
data

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
data[data % 2 == 0] = 0
data

array([ 0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0])