# Numpy Playlist
* https://www.youtube.com/watch?v=6puhu5ulFSE&list=PLmRclvVt5Dtlgy6PordwKtiUr7fwjuhfz&index=1

In [7]:
import numpy as np
a : list[int] = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [8]:
myArr = np.array(a)
myArr

array([1, 2, 3, 4])

In [14]:
user_input = int(input('Enter array size'))
data = []
for i in range(user_input):
    array_data = int(input(f'Enter {i+1} number'))
    data.append(array_data)
my_array = np.array(data)
my_array


Enter array size 5
Enter 1 number 4
Enter 2 number 3
Enter 3 number 2
Enter 4 number 2
Enter 5 number 4


array([4, 3, 2, 2, 4])

# Two Diamensional Arrays

In [15]:
data = [[1,2,3], [4,5,6],[7,8,9]]
myArray = np.array(data)
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
myArray.ndim

2

In [18]:
myArray.shape

(3, 3)

In [21]:
# print 0
newArray = np.zeros(7)
newArray

array([0., 0., 0., 0., 0., 0., 0.])

In [23]:
newArray = np.zeros((2, 3))
newArray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# For Diagonals
newArray = np.eye(5)
newArray

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# make diagonals 1 and rest 0
newArray = np.eye(3,4)
newArray

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [30]:
# pulls diagonals
myArray = np.diag([2,3,4])
myArray

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [31]:
np.diag(myArray)

array([2, 3, 4])

In [37]:
# generate random numbers in a given range (start, end not included, values)
myArray = np.random.randint(2,89,5)
myArray

array([77, 13, 18,  9, 69])

In [39]:
# generate random numbers between 0 and 1
myArray = np.random.rand(4)
myArray

array([0.05616279, 0.94488975, 0.19707611, 0.31111503])

In [40]:
# generate values close to 1 and could be -ve
myArray = np.random.randn(4)
myArray

array([ 0.76737777, -0.03151176,  0.35619412, -1.02362695])

In [42]:
# array conversions (reshaping)
myArray = np.random.randint(2,77,12)
myArray

array([30, 76, 48, 61, 43, 28, 22,  4, 51, 40, 49,  9])

In [44]:
myArray.reshape(3,4)

array([[30, 76, 48, 61],
       [43, 28, 22,  4],
       [51, 40, 49,  9]])

In [45]:
myArray.reshape(12)
myArray

array([30, 76, 48, 61, 43, 28, 22,  4, 51, 40, 49,  9])

In [51]:
# auto-populate the -1 column
# must be stored in a new variable
dataArray = np.random.randint(2,77,12)
data = dataArray.reshape(4,-1)
data

array([[14, 12,  2],
       [62, 26, 59],
       [58,  3, 22],
       [49, 16, 40]])

In [63]:
# seed function maintains the values and not chang
np.random.seed(1)
dataArray = np.random.randint(2,77,12)
dataArray

array([39, 14, 74, 11,  7, 66, 18,  3, 73,  8, 27, 52])

In [ ]:
# 2D array with user input. A bit tricky and needs practice
* https://www.youtube.com/watch?v=iFJHiZkLIi8&list=PLmRclvVt5Dtlgy6PordwKtiUr7fwjuhfz&index=10

In [64]:
# Slicing and Indexing of 2D arrays
data

array([[14, 12,  2],
       [62, 26, 59],
       [58,  3, 22],
       [49, 16, 40]])

In [65]:
data[2][1]

3

In [66]:
# Slicing Syntax => data[row_range, column_range]
data

array([[14, 12,  2],
       [62, 26, 59],
       [58,  3, 22],
       [49, 16, 40]])

In [67]:
data[1:3]

array([[62, 26, 59],
       [58,  3, 22]])

In [68]:
data[1:3,1:3]

array([[26, 59],
       [ 3, 22]])

In [72]:
newArray = np.random.randint(2,66,30)
newArray

array([13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51, 57, 32, 34, 24, 15,
       43, 11,  9, 65, 63, 24, 59,  3,  2, 62, 19, 10, 26])

In [78]:
multiArray = newArray.reshape(6,-1)
multiArray

array([[13, 62, 44, 30, 31],
       [16, 52,  6, 25, 25],
       [43, 51, 57, 32, 34],
       [24, 15, 43, 11,  9],
       [65, 63, 24, 59,  3],
       [ 2, 62, 19, 10, 26]])

In [82]:
multiArray[3:6,2:5]

array([[43, 11,  9],
       [24, 59,  3],
       [19, 10, 26]])