# Numpy Playlist
* https://www.youtube.com/watch?v=6puhu5ulFSE&list=PLmRclvVt5Dtlgy6PordwKtiUr7fwjuhfz&index=1

In [3]:
import numpy as np
a : list[int] = [1, 2, 3, 4]
a

[1, 2, 3, 4]

In [4]:
myArr = np.array(a)
myArr

array([1, 2, 3, 4])

In [5]:
user_input = int(input('Enter array size'))
data = []
for i in range(user_input):
    array_data = int(input(f'Enter {i+1} number'))
    data.append(array_data)
my_array = np.array(data)
my_array


array([3, 2, 3, 4])

# Two Diamensional Arrays

In [6]:
data = [[1,2,3], [4,5,6],[7,8,9]]
myArray = np.array(data)
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
myArray.ndim

2

In [8]:
myArray.shape

(3, 3)

In [10]:
# print 0
newArray = np.zeros(7)
newArray

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
newArray = np.zeros((2, 3))
newArray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# For Diagonals
newArray = np.eye(5)
newArray

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
# make diagonals 1 and rest 0
newArray = np.eye(3,4)
newArray

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
# pulls diagonals
myArray = np.diag([2,3,4])
myArray

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [15]:
np.diag(myArray)

array([2, 3, 4])

In [16]:
# generate random numbers in a given range (start, end not included, values)
myArray = np.random.randint(2,89,5)
myArray

array([65, 85,  7, 61, 35])

In [17]:
# generate random numbers between 0 and 1
myArray = np.random.rand(4)
myArray

array([0.35919953, 0.91520916, 0.46890207, 0.2534493 ])

In [18]:
# generate values close to 1 and could be -ve
myArray = np.random.randn(4)
myArray

array([ 3.44951003,  0.38025873, -0.63757072, -0.22564972])

In [19]:
# array conversions (reshaping)
myArray = np.random.randint(2,77,12)
myArray

array([36, 65, 50, 15, 41, 49, 22, 60, 34, 31, 53, 12])

In [20]:
myArray.reshape(3,4)

array([[36, 65, 50, 15],
       [41, 49, 22, 60],
       [34, 31, 53, 12]])

In [21]:
myArray.reshape(12)
myArray

array([36, 65, 50, 15, 41, 49, 22, 60, 34, 31, 53, 12])

In [22]:
# auto-populate the -1 column
# must be stored in a new variable
dataArray = np.random.randint(2,77,12)
data = dataArray.reshape(4,-1)
data

array([[35, 12, 50],
       [29, 51, 41],
       [65, 68, 48],
       [ 3,  4, 26]])

In [23]:
# seed function maintains the values and not chang
np.random.seed(1)
dataArray = np.random.randint(2,77,12)
dataArray

array([39, 14, 74, 11,  7, 66, 18,  3, 73,  8, 27, 52])

In [25]:
# 2D array with user input. A bit tricky and needs practice
# https://www.youtube.com/watch?v=iFJHiZkLIi8&list=PLmRclvVt5Dtlgy6PordwKtiUr7fwjuhfz&index=10

In [26]:
# Slicing and Indexing of 2D arrays
data

array([[35, 12, 50],
       [29, 51, 41],
       [65, 68, 48],
       [ 3,  4, 26]])

In [27]:
data[2][1]

68

In [66]:
# Slicing Syntax => data[row_range, column_range]
data

array([[14, 12,  2],
       [62, 26, 59],
       [58,  3, 22],
       [49, 16, 40]])

In [28]:
data[1:3]

array([[29, 51, 41],
       [65, 68, 48]])

In [29]:
data[1:3,1:3]

array([[51, 41],
       [68, 48]])

In [30]:
newArray = np.random.randint(2,66,30)
newArray

array([22, 64, 39, 20, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [31]:
multiArray = newArray.reshape(6,-1)
multiArray

array([[22, 64, 39, 20, 22],
       [13, 62, 44, 30, 31],
       [16, 52,  6, 25, 25],
       [43, 51, 57, 32, 34],
       [24, 15, 43, 11,  9],
       [65, 63, 24, 59,  3]])

In [32]:
multiArray[3:6,2:5]

array([[57, 32, 34],
       [43, 11,  9],
       [24, 59,  3]])

In [33]:
# view vs copy
newArray

array([22, 64, 39, 20, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [39]:
myView = newArray[2:4]
myView

array([39, 20])

In [40]:
myView[:] = 0
myView

array([0, 0])

In [41]:
newArray

array([22, 64,  0,  0, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])

In [45]:
myCopy = newArray[4:8].copy()
myCopy[:] = 5
myCopy


array([5, 5, 5, 5])

In [46]:
newArray

array([22, 64,  0,  0, 22, 13, 62, 44, 30, 31, 16, 52,  6, 25, 25, 43, 51,
       57, 32, 34, 24, 15, 43, 11,  9, 65, 63, 24, 59,  3])