In [3]:
import numpy as np

data : np.ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
data.itemsize

8

In [5]:
from nptyping import NDArray, Shape
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1, 11)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
import numpy as np
from typing import Any
from nptyping import NDArray

data: NDArray[Shape["2, 5"], Any] = np.arange(1, 11).reshape(2, 5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
data : NDArray[Shape["4"], Any] = np.arange(3, 7)
bool_data : NDArray[Shape["4"], Any] = np.array([True, False, False, False])
data[bool_data]

array([3])

In [11]:
data[data % 2 == 0]

array([4, 6])

In [9]:
# in1d function returns true false
# intersect1d returns the values

# First array (we want to check if its elements are in the second array)
arr1 = np.array([1, 2, 3, 4, 5])

# Second array (reference array to check against)
arr2 = np.array([2, 4, 6, 8])

# Use np.in1d to check if elements of arr1 are in arr2
result = np.in1d(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Result of np.in1d:", result)


Array 1: [1 2 3 4 5]
Array 2: [2 4 6 8]
Result of np.in1d: [False  True False  True False]


In [15]:
new_data = np.where(data%2 == 0)
new_data


(array([0, 0, 1, 1, 1]), array([1, 3, 0, 2, 4]))

In [21]:
# size can be replaced with *
x : NDArray[Shape["5"], Any] = np.array([1, 5, 3, 42, 5])

y : NDArray[Shape["5"], Any] = np.array([6, 7, 8, 9, 10])

my_data = np.where(x > y, x, y)
my_data

array([ 6,  7,  8, 42, 10])