# Numpy

## Introduction
- Vector => One dimensional array
- Matrix => Two dimensional array
- Tensor => Three dimensional array

## Installation
- Install Conda and everything will be installed automatically
- Run command ```conda install numpy``` in case of any issues

## Helpful Shortcuts
- ctr + enter => execute 
- shift + enter => execute
- ```b``` to add cell below and ```a``` to add cell above
- - dd to delete cell

## 1D Array

In [2]:
import numpy as np
list_data : list[int] = [1, 2, 3, 4, 5]
list_data

[1, 2, 3, 4, 5]

In [3]:
data = np.array(list_data)
data

array([1, 2, 3, 4, 5])

In [10]:
import numpy as np

list_data: list[int] = []

try:
    # Get list size from the user
    list_size = int(input('Enter list size: '))

    # Ensure that the input is a positive integer
    if list_size <= 0:
        raise ValueError("List size must be a positive integer.")
    
    # Collect user inputs for list data
    for i in range(list_size):
        try:
            user_input = int(input(f'Enter value {i + 1}: '))
            list_data.append(user_input)
        except ValueError:
            raise ValueError(f"Invalid input at position {i + 1}, expected an integer.")

    # Convert list to a NumPy array
    data = np.array(list_data)
    print(f"Data as NumPy array: {data}")

except ValueError as e:
    print(f"Error: {e}")


Enter list size:  4
Enter value 1:  1
Enter value 2:  2
Enter value 3:  3
Enter value 4:  4


Data as NumPy array: [1 2 3 4]


## 2D Array

### Numpy Functions

In [12]:
my_list : list[list[int]] = [[1, 2, 3], [2, 3, 4], [3, 4, 5]]
data = np.array(my_list)
data

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [13]:
np.shape(data) # gives shape of array

(3, 3)

In [14]:
np.ndim(data) # give array info

2

In [15]:
np.zeros(3) # to create array with 0

array([0., 0., 0.])

In [16]:
np.ones(3) # to create array with 1

array([1., 1., 1.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
eye_function = np.eye(3,4)
eye_function

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
data = np.diag([2, 3, 4, 4])
data

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]])

In [27]:
np.diag(data) # means also reversibile

array([2, 3, 4, 4])

In [30]:
data = np.random.randint(2, 10, 5) # randint(min, max, total) and remember max not included
data

array([7, 4, 4, 2, 5])

In [31]:
data = np.random.rand(4) # give 4 values in between 0 and 1
data

array([0.36266019, 0.00628815, 0.89998648, 0.06902216])

In [32]:
data = np.random.rand(2, 3)
data

array([[0.68458626, 0.81105811, 0.83778904],
       [0.6751466 , 0.13458231, 0.47004189]])

In [33]:
data = np.random.randn(2, 3) # generates values close to 0
data

array([[ 1.1491672 ,  0.76867357, -0.82750572],
       [-0.07244173,  0.8346383 , -0.018273  ]])

In [3]:
my_list = [1, 2, 4, 5, 3, 2] # Sample data
data = np.array(my_list)
data

array([1, 2, 4, 5, 3, 2])

In [7]:
sum = 0 # Slicing and indexing
for i in data:
    print(i)  
    sum += i
print(f'Sum is {sum}')
data[-4:]

1
2
4
5
3
2
Sum is 17


array([4, 5, 3, 2])

In [12]:
# reshape array
data = np.random.randint(2, 100, 12)
print(data.reshape(3, 4))
print(data.shape)
print(data.reshape(4, 3))
print(data.reshape(12))

[[87 19 56 56]
 [58 78 43 37]
 [51 49 62 22]]
(12,)
[[87 19 56]
 [56 58 78]
 [43 37 51]
 [49 62 22]]
[87 19 56 56 58 78 43 37 51 49 62 22]


In [15]:
print(data)
# we can let the program to decide by itself by specifying number of rows or columns to -1
data.reshape(3, -1)

[87 19 56 56 58 78 43 37 51 49 62 22]


array([[87, 19, 56, 56],
       [58, 78, 43, 37],
       [51, 49, 62, 22]])

In [32]:
# seed is used to get the same values from randint
np.random.seed(2) # 2 can be any number
data = np.random.randint(2, 99, 10)
data

array([42, 17, 74, 24, 45, 84, 77,  9, 36, 51])